Multiple improvements
TonyCrane/mkdocs-statistics-plugin pull request #18
Opened 2024-09-07 21:29 UTC by Xiaokang2022

* Fixed a bug where text was not displayed when the "read_time" was less than 1 branch; #16 
* Added support for the English language; #17 
* Added statistics on the number of images; #12

2024-09-07 21:30 UTC, Xiaokang2022 commented
效果预览见：https://xiaokang2022.github.io/tkintertools/ #12 

可以通过预览网页顶部切换语言来查看效果，也可以直接看：https://xiaokang2022.github.io/tkintertools/en/ #17

2024-09-07 21:36 UTC, Xiaokang2022 commented
对图片的统计没有计算其阅读时间，只是做了统计，另外，可以通过 `{{ images }}` 来将数据显示到页面上

目前只对 mkdocs-material 主题做了测试，其它的没有

2024-09-07 21:38 UTC, Xiaokang2022 commented
对语种的支持只做了简体中文和英语的，自动从 `config.theme.language` 中获取当前页面主题，没有做 `locale` 的配置选项

2024-09-09 09:53 UTC, TonyCrane commented on mkdocs_statistics_plugin/templates/page_statistics.html
> +{% endif %}
不要改模板，你把 icon 按照你的喜好改了是什么意思呢

另外还引入了 busuanzi_value_page_pv 这种东西

想改模板自己用的时候完全可以自定义模板，不要随便改 repo 里的

2024-09-09 10:01 UTC, TonyCrane requested changes
#16 的问题不该这么改，问题在于控制是否显示阅读时间的选项是 `page_read_time`，应该把这个传进模板，而不是只传 `read_time`。你这样改是全部显示阅读时间，那 `page_read_time` 就没用了。

另外既然加了图片计数，就也要加一个是否显示图片计数的选项，然后 `page.meta` 也要像 #15 一样加。

另外记住多个功能不要堆在一个 PR 里。

2024-09-09 10:01 UTC, TonyCrane commented on mkdocs_statistics_plugin/templates/page_statistics.html
> +{% endif %}
不要改模板，你把 icon 按照你的喜好改了是什么意思呢

另外还引入了 busuanzi_value_page_pv 这种东西

想改模板自己用的时候完全可以自定义模板，不要随便改 repo 里的

2024-09-09 10:01 UTC, TonyCrane commented on mkdocs_statistics_plugin/plugin.py
> +        self.images += len(re.findall("<img.*>", markdown)) + len(re.findall("!\\[.*\\]\\(.*\\)", markdown))
图片的 re 用 `r'!\[[^\]]*\]\([^)]*\)'`，后面不是有写吗，为什么不统一

2024-09-09 10:01 UTC, TonyCrane commented on mkdocs_statistics_plugin/plugin.py
> +            images = len(re.findall("<img.*>", markdown)) + len(re.findall("!\\[.*\\]\\(.*\\)", markdown))
图片的 re 用 `r'!\[[^\]]*\]\([^)]*\)'`，后面不是有写吗，为什么不统一

2024-09-09 10:13 UTC, Xiaokang2022 commented on mkdocs_statistics_plugin/templates/page_statistics.html
> +{% endif %}
不好意思，只要第一个提交的内容，第二个提交是我自己的定制内容

2024-09-09 11:03 UTC, Xiaokang2022 commented
新建了一个分支，原来的不好修改，提交了新的 PR(#19 )，这个就关了

2024-09-09 11:03 UTC, closed without merging